### ISSUE TITLE
Not found error

### ISSUE THREAD

**Issue by BearOutThere** [codeparticle/nativescript-doorbell.io#2]
When running 
tns plugin add nativescript-doorbell.io

getting not found error
`
npm ERR! code E404
npm ERR! 404 Not Found: nativescript-doorbell.io@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bear/.npm/_logs/2018-05-03T10_47_00_189Z-debug.log
Command npm install nativescript-doorbell.io --save failed with exit code 1
`

Is anybody experiencing this problem?

**Comment by BearOutThere** [comment]
bump.   still cannot install the plugin.  any suggestions?

**Comment by codeparticle** [comment]
Looking into it

**Comment by codeparticle** [comment]
We just re-deployed the plugin on the npm registry, could you try installing it again?

**Comment by BearOutThere** [comment]
It's working now.  Thank you.
