### ISSUE TITLE
Plugin crashes on showDoorbellFeedback

### ISSUE THREAD

**Issue by BearOutThere** [codeparticle/nativescript-doorbell.io#3]
Installed the plugin from a local directory because npm install errors out ( issue #2 )
Setup the plugin for android in a page view model like so:

**temp-page.xml**
`
\<Page
    navigatingTo="onNavigatingTo"  
    xmlns="http://schemas.nativescript.org/tns.xsd">

   \<GridLayout rows="*, auto" columns="*">
        \<Label text="Just label" textWrap="true" row="0" col="0" verticalAlign="center" />
        \<Button text="Feedback test" tap="{{ showMessage }}" row="1" col="0" />

   \</GridLayout>
\</Page>
`

**temp-view-model.ts:**
`
import { Observable } from "data/observable";
import { showDoorbellFeedback } from "nativescript-doorbell.io";

export class TempViewModel extends Observable {
    public viewController: any;
    private appId: string;
    private appKey: string;

    constructor() {
        super();
        this.viewController = null;
        this.appId = "8190";
        this.appKey = "Ue4WZwSlHfxW3tsj6ejwtODZs5GT9wPb0bLeaszrblxJVjEOi79x2Lfxkm2BnP8M";

    }
    public showMessage(): void {
        showDoorbellFeedback(this.appId, this.appKey, this.viewController);
    }
}
`
**Error:** 
`
System.err: TypeError: io.doorbell.android.Doorbell is not a constructor
System.err: File: "file:///data/data/com.app90dayreporter/files/app/tns_modules/nativescript-doorbell.io/index.js, line: 8, column: 21
`

The error happens on line 8 in index.js
`
    const feedback = new io.doorbell.android.Doorbell(application.android.currentContext, parseInt(appId), appKey);

`

Perhaps installing from a local folder is the cause but i'm not sure where to look.  Any suggestions would be greatly appreciated.

**Comment by codeparticle** [comment]
@bearoutthere 
Please attempt to install the plugin from the npm registry and try again.
Also, let us know what version nativescript you are using.

**Comment by BearOutThere** [comment]
It's working now.  Thank you very much.
