### ISSUE TITLE
How to specify Doorbell.io options through plugin?

### ISSUE THREAD

**Issue by BearOutThere** [codeparticle/nativescript-doorbell.io#4]
Doorbell.io provides several options for their api calls.  Is there a way to set those options through the plugin?  For example, in my app i already have user's email and would like to set it programatically.
Thanks.

**Comment by codeparticle** [comment]
Not currently, but that would be something rather simple to implement in the plugin as it involves passing in the right params and calling the platform specific function on the index.js function to apply the params.

We could possible work on this eventually, but if you want to contribute, feel free.

**Comment by BearOutThere** [comment]
Thank you.  I'll let you know when i implement this.
