### ISSUE TITLE
nativeElement attribute does not exist on StackLayout class

### ISSUE THREAD

**Issue by BearOutThere** [codeparticle/nativescript-doorbell.io#5]
In the instructions it states: 

```
const viewController = isIOS ? this.feedbackContainer.nativeElement.ios.viewController : null;
FeedbackContainer is a StackLayout in the html of the page where the function is called from. It does not need to have any particular alignment. 
```

According to the NS API documentation (and VSC linting) nativeElement does not exist on the StackLayout class nor its parent classes.   There is nativeView though.  What should be used?

**Comment by Ericky14** [comment]
@bearoutthere Whichever one as long as you are able to access the viewController. I am not sure if it has been deprecated, but nativeElement has always been a part of layout elements.
